### ISSUE TITLE
Hur ska VUXGR-kurser, som inte har ämnen, behandlas?

### ISSUE THREAD

**Issue by fornwall** [stefan-jonasson/curriculum-parser#11]
Kurser inom [Kommunal vuxenutbildning på grundläggande nivå](https://www.skolverket.se/om-skolverket/publikationer/visa-enskild-publikation?_xurl_=http%3A%2F%2Fwww5.skolverket.se%2Fwtpub%2Fws%2Fskolbok%2Fwpubext%2Ftrycksak%2FBlob%2Fpdf3882.pdf%3Fk%3D3882) är inte grupperade i ämnen, och har direkt `Purpose` i kurserna.

Ett första förslag är att göra något i stil med:

```kotlin
data class GySubject(val name: String,
                   val description: String,
                   val code: String,
                   val purposes: List<Purpose>
)

data class GyCourse(val name: String,
                  val description: String,
                  val code: String,
                  val point: Int,
                  val centralContent: List<CentralContent>? = null,
                  val knowledgeRequirement: List<KnowledgeRequirement>? = null
)

data class VuxGrCourse(val name: String,
                  val description: String,
                  val code: String,
                  val point: Int,
                  val centralContent: List<CentralContent>? = null,
                  val knowledgeRequirement: List<KnowledgeRequirement>? = null,
                  val purposes: List<Purpose>
)
```

Dvs, ha olika data klasser för olika skolformer. Vad sägs?

**Comment by stefan-jonasson** [comment]
Jag håller på med en lösning, läser in det i samma struktur, lägger bara till en kurs under varje ämne.

**Comment by stefan-jonasson** [comment]
Kolla på #12 som förslag på lösning

**Comment by stefan-jonasson** [comment]
Ok, inser att jag inte svarade på frågan. 
Skulle gärna vilja ha samma struktur för allt.

En lösning kan vara att vi alltid på ämnesnivå lägger 
- purposes
- centralContent
- knowledgeRequirement

Dessa har sedan olika villkor 
 - yeargroup (Kan vara olika i grundskolan, bara en årskurs för kkr och ett span för cc)
 - courseCode 
 - Kanske finns något annat?

@fornwall Vad tror du?
