### ISSUE TITLE
VUXGR - Description innehåller html 

### ISSUE THREAD

**Issue by stefan-jonasson** [stefan-jonasson/curriculum-parser#20]
Felaktig html behöver rensas bort från description
`<p align="left">Språk är människans främsta redskap för reflektion, kommunikation och kunskapsutveckling. Genom språket utvecklar människor sin identitet, uttrycker känslor och tankar och förstår hur andra känner och tänker. Att ha ett rikt och varierat språk är betydelsefullt för att kunna förstå och verka i ett samhälle där kulturer, livsåskådningar, generationer och språk möts.`

**Comment by teolag** [comment]
Jag jobbar på den här

**Comment by teolag** [comment]
Pull request #30 finns nu för review
