### ISSUE TITLE
Problem med GY - DAG (Dansgestaltning för yrkesdansare)

### ISSUE THREAD

**Issue by teolag** [stefan-jonasson/curriculum-parser#21]
Upptäckte att parsern inte kan hitta några bullets i <purpose> i ämnet "Dansgestaltning för yrkesdansare" på gymnasiet. I xml:en har de själva skrivit in siffror och texter 
```
1. Text
2. Text
osv...
```
istället för märka upp med `<ol><li>` som i de andra ämnena.
Hur gör vi i det här fallet? Är det något man kan be skolverket fixa till eller ska vi med hjälp av parsern och lite replace försöka laga detta? Har du gjort något liknande för andra ämnen?

curriculum-parser-service:
http://localhost:8088/subject/GY/DAG

Skolverket:
https://www.skolverket.se/laroplaner-amnen-och-kurser/gymnasieutbildning/gymnasieskola/sok-amnen-kurser-och-program/subject.htm?subjectCode=DAG&lang=sv&tos=gy

**Comment by stefan-jonasson** [comment]
Hej!
Detta borde vi lösa i parsern ( och meddela skolverket). Det har vi gjort på andra ställen där de inte följer sin egen struktur.

**Comment by stefan-jonasson** [comment]
Frågan är hur vi borde fixa det. 
Skall vi ha med siffran i texten eller skall vi plocka bort den?

Jag ser helst att vi inte förvanskar materialet från skolverket, men siffran blir väldigt konstig när meningen används utanför listan.

**Comment by teolag** [comment]
Jo precis. I det här läget är det ju ganska tydligt att siffran är en del av numreringen i listan så om vi tar bort den från texten har vi inte förvanskat materialet tycker jag.

Har du någon kontakt på skolverket som du brukar höra av dig till? Ska du eller jag göra det?

**Comment by stefan-jonasson** [comment]
Jag kan höra av mig till dem, en PR är på gång också!

**Comment by stefan-jonasson** [comment]
Detta är nu fixat i PR #24

**Comment by teolag** [comment]
Great!  ser bra ut!
