### ISSUE TITLE
Nu missar vi en del rubriker som finns i Skolverkets material 

### ISSUE THREAD

**Issue by stefan-jonasson** [stefan-jonasson/curriculum-parser#6]
Vi behöver returnera alla texter genom parsern så att den i teorin kan återskapa det ursprungliga dokumentet.

**Comment by fornwall** [comment]
Är det MAIN_HEADING från https://github.com/stefan-jonasson/curriculum-parser/pull/2 du avser här (med åtminstone [Djurens biologi, 100 poäng](https://www.skolverket.se/laroplaner-amnen-och-kurser/gymnasieutbildning/gymnasieskola/sok-amnen-kurser-och-program/subject.htm?subjectCode=BIG&lang=sv&tos=gy) som ett specialfall där `<i>` är huvudrubrik)? Jag kan isf göra det så snart https://github.com/stefan-jonasson/curriculum-parser/pull/10 är inne, så ändringarna inte skapar konflikter med varandra.

**Comment by stefan-jonasson** [comment]
Avvakta med detta, jag har det på g

**Comment by stefan-jonasson** [comment]
Mergat till Master
