### ISSUE TITLE
Uppdatera testerna för att ladda en fixerad version av skolverkets filer

### ISSUE THREAD

**Issue by stefan-jonasson** [stefan-jonasson/curriculum-parser#9]
Efter #4 är klar så lägger vi in de testade versionerna av skolverkets material som en test resurs.

**Comment by fornwall** [comment]
Det är inte bara testerna som har behov av fixerade/väldefinierade versioner av skolverkets material, utan även när funktionalitet används för att importera in materialet i ett system finns behovet, för spårbarhet och reproducerbarhet.

Ska vi lägga in tarfilerna direkt i projektet? Då kan SkolverketFile använda dessa, både för tester och för faktiskt funktionalitet när projektet används som bibliotek. Det bär emot lite att lägga in filer som inte är källkod i projektet, men de är ju inte särskilt stora så kanske är det mest praktiska.

Alternativt ser vi till att lägga upp versionshanterade filer externt (sålänge inte skolverket hanterar detta själva), i stil med https://some.domain/skolverket-files/2018-02-03/syllabus.tgz, och laddar ner dom vid körning med checksum-kontroll.

**Comment by stefan-jonasson** [comment]
Vill att vi håller nere scopet för parse-biblioteket för att inte bygga in för mycket av vårt eget tänk i lösningen. 

Har en bättre ide angående versionshanteringen. 

Då det krävs en ny skolFs för varje förändring så kan vi eventuellt använda `<skolfsId>2010:84</skolfsId>`  som version för varje ämne. Det blir då versionerat på ämnesnivå på ett sätt där vi kan utbyta material mellan leverantörer och förstå varandras innehåll, så vidare vi inte genererat det med olika versioner av parsern.

**Comment by fornwall** [comment]
> Då det krävs en ny skolFs för varje förändring

Är det alltså så att de inte gör justeringar (förtydligar meningar, layoutfel eller liknande) utan en ny skolFs? I så fall låter ju det bra med versionshanterat på skolFS-nivå.

Men en kopia av filerna behövs väl fortfarande läggas upp någonstans? För just nu kan väl skolverket uppdatera t.ex. `syllabus.tgz`, och då finns det inte någon möjlighet att få tag på den gamla versionen (vilket det kan finnas behov av för att jämföra ändringar, eller för att under en övergångstid stödja gamla versionen).

**Comment by stefan-jonasson** [comment]
Fick svar från skolverket angående skolfsid:
Vi är medvetna om problematiken och kommer att åtgärda det så fort vi har möjlighet. Med största sannolikhet kommer det att vara åtgärdat till den 18 juni då vi lanserar nya www.skolverket.se, som kommer att hämta styrdokumentsdata direkt från ESSET.
